//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace html2openxml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredefinedStyles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredefinedStyles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("html2openxml.Properties.PredefinedStyles", typeof(PredefinedStyles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Caption&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;caption&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;200&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b /&gt;
        ///    &lt;w:bCs /&gt;
        ///    &lt;w:color w:val=&quot;5B9BD5&quot; w:themeColor=&quot;accent1&quot; /&gt;
        ///    &lt;w:sz w:val=&quot;18&quot; /&gt;
        ///    &lt;w:szCs w:val=&quot;18&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;character&quot; w:styleId=&quot;EndnoteReference&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;endnote reference&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot; /&gt;
        ///  &lt;w:semiHidden /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:vertAlign w:val=&quot;superscript&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string EndnoteReference {
            get {
                return ResourceManager.GetString("EndnoteReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;EndnoteText&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;endnote text&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:semiHidden /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;20&quot; /&gt;
        ///    &lt;w:szCs w:val=&quot;20&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string EndnoteText {
            get {
                return ResourceManager.GetString("EndnoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;character&quot; w:styleId=&quot;FootnoteReference&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;footnote reference&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot; /&gt;
        ///  &lt;w:semiHidden /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:vertAlign w:val=&quot;superscript&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string FootnoteReference {
            get {
                return ResourceManager.GetString("FootnoteReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;FootnoteText&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;footnote text&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:semiHidden /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;20&quot; /&gt;
        ///    &lt;w:szCs w:val=&quot;20&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string FootnoteText {
            get {
                return ResourceManager.GetString("FootnoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading1&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 1&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading1Char&quot; /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;480&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;0&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w:eastAsiaTheme=&quot;majorEast [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading2&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 2&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading2Char&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;200&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;1&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading2 {
            get {
                return ResourceManager.GetString("Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading3&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 3&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading3Char&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;200&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;2&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading3 {
            get {
                return ResourceManager.GetString("Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading4&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 4&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading4Char&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;200&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;3&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading4 {
            get {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading5&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 5&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading5Char&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;200&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;4&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading5 {
            get {
                return ResourceManager.GetString("Heading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading6&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;heading 6&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Heading6Char&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext /&gt;
        ///    &lt;w:keepLines /&gt;
        ///    &lt;w:spacing w:before=&quot;200&quot; w:after=&quot;0&quot; /&gt;
        ///    &lt;w:outlineLvl w:val=&quot;5&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot; w:hAnsiTheme=&quot;majorHAnsi&quot; w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading6 {
            get {
                return ResourceManager.GetString("Heading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;character&quot; w:styleId=&quot;Hyperlink&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Hyperlink&quot; /&gt;
        ///  &lt;w:unhideWhenUsed /&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:color w:val=&quot;0000FF&quot; w:themeColor=&quot;hyperlink&quot; /&gt;
        ///    &lt;w:u w:val=&quot;single&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; w:type=&quot;paragraph&quot; w:styleId=&quot;IntenseQuote&quot;&gt;
        ///  &lt;w:name w:val=&quot;Intense Quote&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;IntenseQuoteChar&quot; /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:pBdr&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:color=&quot;5B9BD5&quot; w:themeColor=&quot;accent1&quot; w:sz=&quot;4&quot; w:space=&quot;10&quot; /&gt;
        ///      &lt;w:bottom w:val=&quot;single&quot; w:color=&quot;5B9BD5&quot; w:themeColor=&quot;accent1&quot; w:sz=&quot;4&quot; w:space=&quot;10&quot; /&gt;
        ///    &lt;/w:pBdr&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntenseQuote {
            get {
                return ResourceManager.GetString("IntenseQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;ListParagraph&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;List Paragraph&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;720&quot; /&gt;
        ///    &lt;w:contextualSpacing /&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string ListParagraph {
            get {
                return ResourceManager.GetString("ListParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Quote&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Quote&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot; /&gt;
        ///  &lt;w:link w:val=&quot;QuoteChar&quot; /&gt;
        ///  &lt;w:qFormat /&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:i /&gt;
        ///    &lt;w:iCs /&gt;
        ///    &lt;w:color w:val=&quot;000000&quot; w:themeColor=&quot;text1&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;character&quot; w:styleId=&quot;QuoteChar&quot; w:customStyle=&quot;1&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Quote Char&quot; /&gt;
        ///  &lt;w:link w:val=&quot;Quote&quot; /&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:i /&gt;
        ///    &lt;w:iCs /&gt;
        ///    &lt;w:color w:val=&quot;000000&quot; w:themeColor=&quot;text1&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string QuoteChar {
            get {
                return ResourceManager.GetString("QuoteChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;w:style w:type=&quot;table&quot; w:styleId=&quot;TableGrid&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Table Grid&quot; /&gt;
        ///  &lt;w:basedOn w:val=&quot;TableNormal&quot; /&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:tblPr&gt;
        ///    &lt;w:tblInd w:w=&quot;0&quot; w:type=&quot;dxa&quot; /&gt;
        ///    &lt;w:tblBorders&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:color=&quot;auto&quot; w:sz=&quot;4&quot; w:space=&quot;0&quot; /&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:color=&quot;auto&quot; w:sz=&quot;4&quot; w:space=&quot;0&quot; /&gt;
        ///      &lt;w:bottom w:val=&quot;single [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableGrid {
            get {
                return ResourceManager.GetString("TableGrid", resourceCulture);
            }
        }
    }
}
